import './globals.css'
import { Inter } from 'next/font/google'
import Hero from './components/Hero'
import HeroChatgpt from './components/HeroChatgpt'
import Footer from './components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AI Summarizer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <HeroChatgpt />
      {children}
      <Footer />
      </body>

    </html>
  )
}
